# Generated by Django 3.2.13 on 2023-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.CharField(default='take away', max_length=15),
        ),
    ]
