# Generated by Django 3.2.13 on 2023-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
