# Generated by Django 3.2.13 on 2023-06-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_order_bill_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
