# Generated by Django 3.2.13 on 2023-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_user_order_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_items', models.CharField(max_length=5000)),
                ('name', models.CharField(default='', max_length=50)),
                ('bill_total', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
