# Generated by Django 3.2.13 on 2023-06-09 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
